
defaults: &defaults
  host: localhost  
  adapter: postgresql
  encoding: unicode  
  pool: 5  
  port: 5432
  username: postgres
  password: root
 

development:
  <<: *defaults
  database: react_app_rails_dev

test:
  <<: *defaults
  database: react_app_rails_test